#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
# need to find a way to fix #vision link.  seems to appear due to Intro.md, but works in naviation include.  hmm
bundle exec htmlproofer --file-ignore './_site/Initiatives/index.html','./_site/Intro/index.html' --alt-ignore '#vision' --disable-external ./_site
